tick_rate = 50

[ui]
use_nerd_font_icons = true
ui_scale = 100
orientation = "portrait"
theme = "catppuccin"

# Keybindings
# ----------------------------------------------------------------------------
#
# Channel mode
# ------------------------
[keybindings]

# "ctrl-j" = "select_next_entry"
# "ctrl-k" = "select_prev_entry"

# select_next_entry = ["down", "ctrl-n", "ctrl-j"]
# select_next_entry = ["down", "ctrl-n", "ctrl-j"]
# select_prev_entry = ["up", "ctrl-p", "ctrl-k"]
# select_next_page = "pagedown"
# select_prev_page = "pageup"
# # Scrolling the preview pane
# scroll_preview_half_page_down = "ctrl-d"
# scroll_preview_half_page_up = "ctrl-u"
# # Add entry to selection and move to the next entry
# toggle_selection_down = "tab"
# # Add entry to selection and move to the previous entry
# toggle_selection_up = "backtab"
# # Confirm selection
# confirm_selection = "enter"
# # Copy the selected entry to the clipboard
# copy_entry_to_clipboard = "ctrl-y"
# # Toggle the remote control mode
# toggle_remote_control = "ctrl-r"
# # Toggle the send to channel mode
# toggle_send_to_channel = "ctrl-s"
# # Toggle the help bar
# toggle_help = "ctrl-g"
# # Toggle the preview panel
# toggle_preview = "ctrl-o"


# Shell integration
# ----------------------------------------------------------------------------
#
# The shell integration feature allows you to use television as a picker for
# your shell commands (as well as your shell history with <CTRL-R>).
# E.g. typing `git checkout <CTRL-T>` will open television with a list of
# branches to choose from.

[shell_integration]
# This specifies the default fallback channel if no other channel is matched.
fallback_channel = "files"

[shell_integration.channel_triggers]
# Add your channel triggers here. Each key is a channel that will be triggered
# by the corresponding commands.
# Example: say you want the following commands to trigger the following channels
# when pressing <CTRL-T>:
#          `git checkout`  should trigger the `git-branches` channel
#          `ls`            should trigger the `dirs` channel
#          `cat` and `cp`  should trigger the `files` channel
#
# You would add the following to your configuration file:
# ```
# [shell_integration.channel_triggers]
# "git-branches" = ["git checkout"]
# "dirs" = ["ls"]
# "files" = ["cat", "cp"]
# ```
"alias" = ["alias", "unalias"]
"env" = ["export", "unset"]
"dirs" = ["cd", "ls", "rmdir"]
"files" = [
  "cat",
  "less",
  "head",
  "tail",
  "vim",
  "nano",
  "bat",
  "cp",
  "mv",
  "rm",
  "touch",
  "chmod",
  "chown",
  "ln",
  "tar",
  "zip",
  "unzip",
  "gzip",
  "gunzip",
  "xz",
]
"git-diff" = ["git add", "git restore"]
"git-branch" = [
  "git co",
  "git checkout",
  "git branch",
  "git merge",
  "git rebase",
  "git pull",
  "git push",
]
"docker-images" = ["docker run"]
"git-repos" = ["git clone"]
"channels" = ["tv"]
"testfiles" = ["bun run test", "bun test"]
"npm-scripts" = ["bun run", "npm run"]
"text" = ["rg", "grep"]


[shell_integration.keybindings]
# controls which key binding should trigger tv
# for shell autocomplete
"smart_autocomplete" = "ctrl-t"
# controls which keybinding should trigger tv
# for command history
"command_history" = "ctrl-r"
