[metadata]
name = "testfiles"
description = "A channel to select test files"
requirements = ["fd", "bat"]

[source]
command = ["fd -t f test.ts"]

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }

# [keybindings]
# shortcut = "f1"
# ctrl-f12 = "actions:edit"

# [actions.edit]
# description = "Opens the selected entries with Neovim"
# command = "nvim {}"
# mode = "execute"
